name: abcdef
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - run: cd .github/actions/ && ls -larth
    - name: step1
      uses: ./.github/actions/action.yml